ifneq ($(filter hi6210sft, $(TARGET_DEVICE)),)



LOCAL_PATH := $(call my-dir)

include \$(CLEAR_VARS)
LOCAL_MODULE := hwcustTelephony-common
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := rootdir/framework/hwcustTelephony-common.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := \$(COMMON_JAVA_PACKAGE_SUFFIX)
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_CERTIFICATE := PRESIGNED
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE := hwframework
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := rootdir/framework/hwframework.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := \$(COMMON_JAVA_PACKAGE_SUFFIX)
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_CERTIFICATE := PRESIGNED
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE := hwServices
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := rootdir/framework/hwServices.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := \$(COMMON_JAVA_PACKAGE_SUFFIX)
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_CERTIFICATE := PRESIGNED
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE := hwWifi-service
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := rootdir/framework/hwWifi-service.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := \$(COMMON_JAVA_PACKAGE_SUFFIX)
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_CERTIFICATE := PRESIGNED
include \$(BUILD_PREBUILT)

include \$(CLEAR_VARS)
LOCAL_MODULE := hwTelephony-common
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := rootdir/framework/hwTelephony-common.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := \$(COMMON_JAVA_PACKAGE_SUFFIX)
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_CERTIFICATE := PRESIGNED
include \$(BUILD_PREBUILT)

include $(call all-makefiles-under,$(LOCAL_PATH))

endif
